
let allSites = [
    "303 Boards": "www.303boards.com",
    "35th North": "35thnorth.com",
    "Adrift Shop CA": "www.adriftshop.com",
    "A Ma Maniere": "www.a-ma-maniere.com",
    "Antonioli EU": "antonioli.eu",
    "Analogue": "store.analogue.co",
    "APB Store": "www.apbstore.com",
    "Addict Miami": "www.addictmiami.com",
    "Afew Store": "en.afew-store.com",
    "Albino & Preto": "www.albinoandpreto.com",
    "Alife": "www.alifenewyork.com",
    "All The Right": "alltheright.com",
    "Alumni of NY": "www.alumniofny.com",
    "Amie Leon Dore": "www.aimeleondore.com",
    "ANTA": "anta.com",
    "Arts And Rec Skate Shop": "artsandrecstore.com",
    "Atlas Skateboarding": "shop.atlasskateboarding.com",
    "Asics HK": "www.asics.com.hk",
    "Asphalt NYC": "asphalt-nyc.com",
    "August Shop": "august-shop.com",
    "Awake NY": "awakenyclothing.com",
    "Bad Bunny Adidas": "badbunnyadidas.com",
    "BBBranded CA": "www.bbbranded.com",
    "BKLYN CAP": "bklyncap.com",
    "Baklava Flea Market": "baklavafleamarket.com",
    "Bandier": "www.bandier.com",
    "Bape": "us.bape.com",
    "Bape JP": "jp.bape.com",
    "Be A Spunge": "beaspunge.com",
    "Better Gift Shop": "www.bettergiftshop.com",
    "Billie Eilish Store US": "store.billieeilish.com",
    "Billie Eilish Store CA": "shopca.billieeilish.com",
    "Billionaire Boys Club": "www.bbcicecream.com",
    "Blacklist Board Shop": "blacklistboardshop.com",
    "Black Sheep Skate Shop": "blacksheepskateshop.com",
    "Blends": "www.blendsus.com",
    "Blue Tile Lounge CA": "bluetilelounge.ca",
    "Bode": "bode.com",
    "Bodega": "bdgastore.com",
    "Born X Raised": "bornxraised.com",
    "Bows Arrows Berkeley": "bowsandarrowsberkeley.com",
    "Burn Rubber": "burnrubbersneakers.com",
    "Bratz": "www.bratz.com",
    "Brooklyn Projects": "brooklynprojects.com",
    "CCS": "shop.ccs.com",
    "Crenshaw Skate Club": "crenshawskateclub.com",
    "CRSVR": "crsvr.com",
    "Cactus Plant Flea Market": "cactusplantfleamarket.com",
    "Canary Yellow": "canary---yellow.com",
    "Capsule": "capsule.nyc",
    "Carhartt WIP USA": "us.carhartt-wip.com",
    "Civilized Nation Shop": "civilizednationshop.com",
    "Civil Regime": "shop.civilclothing.com",
    "CNTRBND CA": "www.cntrbndshop.com",
    "Commonwealth FTGG": "commonwealth-ftgg.com",
    "Concepts": "cncpts.com",
    "Corporate Gotem": "corporategotem.com",
    "Coureur Goods": "coureurgoods.com",
    "Courtside CA": "www.courtsidesneakers.com",
    "Creme321": "creme321.com",
    "DarcSport": "shop.darcsport.com",
    "DSMJP E-SHOP": "shop-jp.doverstreetmarket.com",
    "DSML E-SHOP": "shop.doverstreetmarket.com",
    "DSMNY E-SHOP": "shop-us.doverstreetmarket.com",
    "DSMSG E-SHOP": "singapore.doverstreetmarket.com",
    "DTLR": "www.dtlr.com",
    "Denim Exchange": "denimexchangeusa.com",
    "Denim Tears": "denimtears.com",
    "Dime MTL": "dimemtl.com",
    "Dont Give A Putt": "dontgiveaputt.com",
    "Drew House": "thehouseofdrew.com",
    "Drift House": "www.drifthouse.com",
    "Eastside Golf": "eastsidegolf.com",
    "ECapCity": "www.ecapcity.com",
    "Eric E Manuel": "www.ericemanuel.com",
    "Exclusive Fitted": "exclusivefitted.com",
    "Exodus Ride Shop": "exodusrideshop.com",
    "Extra Butter": "extrabutterny.com",
    "Familia Skate": "familiaskate.com",
    "Fear of God": "fearofgod.com",
    "Feature": "feature.com",
    "Final Mouse": "finalmouse.com",
    "Foosh CA": "www.foosh.ca",
    "Foster": "shopfoster.com",
    "Furnace Skate": "www.furnaceskate.com",
    "FUTURA LABORATORIES": "futuralaboratories.com",
    "GBNY": "gbny.com",
    "Gallery Dept": "gallerydept.com",
    "Garage Skate Shop": "garageskateshop.com",
    "Geometric Skate Shop": "www.geometricskateshop.com",
    "GIRLS DONT CRY": "girlsdontcry.shop",
    "Good News Skate Shop CA": "goodnewsskateshop.com",
    "Grinmore Store": "www.grinmorestore.com",
    "Gym Shark": "www.gymshark.com",
    "HLorenzo": "www.hlorenzo.com",
    "Hanon Shop": "www.hanon-shop.com",
    "Hat Club": "www.hatclub.com",
    "Hat Dreams": "www.hatdreams.com",
    "Hatch Golf": "www.hatchgolf.com",
    "Haven Shop": "havenshop.com",
    "Hell Star": "hellstar.com",
    "Hell Star Golden Ticket": "hellstar.com",
    "Hirshleifers": "hirshleifers.com",
    "HOMEBRED": "homebred.com",
    "HUF Worldwide": "hufworldwide.com",
    "Humanmade JP": "humanmade.jp",
    "Humidity": "humiditynola.com",
    "Hush Life Boutique": "hushlifeboutique.com",
    "Icon Board Shop": "www.iconboardshop.com",
    "JD Sports CA": "jdsports.ca",
    "Joe Fresh Goods": "joefreshgoods.com",
    "JJJJound": "www.jjjjound.com",
    "JYW POKECA": "jyw-pokeca.com",
    "Juice": "juicestore.com",
    "JxBalvin": "jbalvin.com",
    "J Balvin Universal Music": "shop.universalmusica.com",
    "KCDC Skate Shop": "kcdcskateshop.com",
    "Kicking It ATX": "kickingit.com",
    "Kicks Crew": "www.kickscrew.com",
    "Kicks Lounge": "kickslounge.com",
    "Kicks Theory": "kickstheory.com",
    "Kinetic Skate Boarding": "kineticskateboarding.com",
    "Kith": "kith.com",
    "Kith Canada": "ca.kith.com",
    "KRS Comics": "krscomics.com",
    "Lady Gaga": "www.ladygaga.com",
    "LDRS 1354": "ldrs1354.com",
    "Labor Skateshop": "laborskateshop.com",
    "Lamb Crafted": "lambcrafted.com",
    "Lapstone and Hammer": "www.lapstoneandhammer.com",
    "Lids HD": "www.lidshd.com",
    "Likelihood": "likelihood.us",
    "Long Beach Skate Co": "lbskate.com",
    "LoveShackFancy": "www.loveshackfancy.com",
    "MCT TOKYO": "mct.tokyo",
    "Mainland Skate & Surf": "mainlandskateandsurf.com",
    "Magnolia Skate Shop": "www.magnoliaskateshop.com",
    "Makeway CA": "shopmakeway.co",
    "MNML": "mnml.la",
    "Mamba & Mambacita": "shop.mambaandmambacita.org",
    "Manorphx": "www.manorphx.com",
    "Mattel Creations": "creations.mattel.com",
    "Maxfield LA": "www.maxfieldla.com",
    "Menu Skate Shop CA": "menuskateshop.com",
    "Meta Store": "www.metastore.com",
    "Millennium Shoes": "millenniumshoes.com",
    "Momentum Cali": "momentumshop.ca",
    "MoMa Design Store": "store.moma.org",
    "My Fitteds": "www.myfitteds.com",
    "Naked Copenhagen": "nakedcph.com",
    "Ninetimes Skateshop CA": "ninetimesskateshop.com",
    "Nike x RTFKT": "rtfkt.com",
    "NJ Skateshop": "njskateshop.com",
    "NHS Skate Direct": "nhsskatedirect.com",
    "Nohble": "nohble.com",
    "NOCTA": "www.nocta.com",
    "Nomad CA": "nomadshop.net",
    "NRML": "nrml.ca",
    "No Comply Skateshop": "nocomplyatx.com",
    "Notre": "www.notre-shop.com",
    "Obey Giant": "obeygiant.com",
    "Olivia Rodrigo": "store.oliviarodrigo.com",
    "Olympia Skate Shop": "olympiaskateshop.com",
    "Oneblockdown ROW": "oneblockdown.com",
    "Oneness Boutique": "www.onenessboutique.com",
    "Orchard Shop": "orchardshop.com",
    "Octobers Very Own": "us.octobersveryown.com",
    "Packer": "packershoes.com",
    "Palace US": "www.palaceskateboards.com",
    "PLA Skateboarding": "www.plaskateboarding.com",
    "Pawnshop Skate Co": "pawnshopskate.com",
    "Patta": "pattaclothing.us",
    "PDP Gaming": "pdp.com",
    "Pharmacy Board Shop": "pharmacyboardshop.com",
    "Phenom": "ca.phenomglobal.com",
    "Premium Goods": "premiumgoods.com",
    "Private Sneakers": "www.privatesneakers.com",
    "Pro Image America": "proimageamerica.com",
    "Prociety Shop": "procietyshop.com",
    "Proper LBC": "properlbc.com",
    "Puffer Reds": "pufferreds.com",
    "Renarts": "renarts.com",
    "Reynolds & Sons": "reynoldsandsons.com",
    "RSVP Gallery": "rsvpgallery.com",
    "Rock City Kicks": "rockcitykicks.com",
    "Rule of Next": "www.ruleofnext.com",
    "Sp5der Worldwide": "kingspider.co",
    "SVRN": "www.svrn.com",
    "Saint Alfred": "www.saintalfred.com",
    "Sandy Liang": "www.sandyliang.info",
    "Sesinko": "sesinko.com",
    "Skate Park of Tampa": "skateparkoftampa.com",
    "Shoe Palace": "www.shoepalace.com",
    "Shop Kings": "www.shopatkings.com",
    "Shop Nice Kicks": "shopnicekicks.com",
    "Shop Overload": "shopoverload.com",
    "ShopWSS": "www.shopwss.com",
    "Size?": "www.size.co.uk",
    "Slam Jam": "us.slamjam.com",
    "Sneakerbox Cali": "sneakerboxshop.ca",
    "Sneaker Junkies": "sneakerjunkiesusa.com",
    "Sneaker Politics": "sneakerpolitics.com",
    "Sneaker Town": "www.sneakertownmia.com",
    "Social Status": "www.socialstatuspgh.com",
    "Sole Classics": "www.soleclassics.com",
    "Solefly": "www.solefly.com",
    "Sole Play": "www.soleplayatl.com",
    "Solestop": "www.solestop.com",
    "Somewhere": "somewhereofficial.com",
    "Specializing In Life": "www.specializinginlife.com",
    "Sports World": "sportsworld165.com",
    "Sporty & Rich": "sportyandrich.com",
    "Spusta Studio Shop": "shop.marqspusta.com",
    "Stadium Status": "www.stadiumstatusla.com",
    "Stanley 1913": "www.stanley1913.com",
    "Stanley 1913 CA": "ca.stanley1913.com",
    "Stashed": "stashedsf.com",
    "Strange Love": "www.strangeloveshop.com",
    "Stussy": "www.stussy.com",
    "Succezz": "succezzthestore.com",
    "Sun Diego Board Shop": "sundiego.com",
    "Super Cool Studios": "getsupercool.com",
    "Supreme EU": "eu.supreme.com",
    "Supreme JP": "jp.supreme.com",
    "Supreme UK": "uk.supreme.com",
    "Supreme US": "us.supreme.com",
    "Swag Golf": "swag.golf",
    "Swell-O-Phonic": "shopswellophonic.com",
    "Takeout NY": "takeoutny.com",
    "Taylor Swift Official Store": "store.taylorswift.com",
    "Taylor Swift Store CA": "storeca.taylorswift.com",
    "Taylor Swift Store UK": "storeuk.taylorswift.com",
    "Telfar": "telfar.net",
    "Tiki Room Skateboards CA": "tikiroomskateboards.com",
    "Time Machine Skate Shop": "timemachineskateshop.com",
    "The Better Generation": "thebettergeneration.com",
    "TheClosetinc CA": "www.theclosetinc.com",
    "The Darkside Initiative": "www.thedarksideinitiative.com",
    "The Premier Store": "thepremierstore.com",
    "There Skateboards": "thereskateboards.com",
    "Todd Snyder": "www.toddsnyder.com",
    "Tom Sachs": "store.tomsachs.com",
    "Tony Brimz": "tonybrimz.com",
    "Tops and Bottoms USA": "www.topsandbottomsusa.com",
    "Travel Skate Shop": "www.travelskateshop.com",
    "Travis Scott": "www.travisscott.com",
    "Tres Bien": "tres-bien.com",
    "Trophy Room": "www.trophyroomstore.com",
    "Two18": "two18.com",
    "UNheardof": "unheardofbrand.com",
    "UPNYC Store": "upnycstore.com",
    "Uprise Skate Shop": "upriseskateshop.com",
    "USA Cap King": "usacapking.com",
    "Undefeated": "undefeated.com",
    "Underground Skate Shop": "www.undergroundskateshop.com",
    "Union": "store.unionlosangeles.com",
    "Val Surf": "valsurf.com",
    "Wales Bonner": "walesbonner.com",
    "WALLHACK": "wallhack.com",
    "We Are Civil": "www.wearecivil.com",
    "Wish ATL": "wishatl.com",
    "wooDstack": "www.woodstack.com",
    "Wutang Clan": "www.thewutangclan.com",
    "Xhibition": "www.xhibition.co",
    "Xtreme Board Shop": "xbusa.com"
]
